server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: doctorplus-backend

  datasource:
    url: jdbc:h2:mem:doctorplus_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # Para banco em arquivo: jdbc:h2:file:./data/doctorplus_db
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # Configuração H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  # Configuração JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create-drop, create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    
#  datasource:
#    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
#    username: ${DB_USERNAME:postgres.yqzjredughrsczqzaker}
#    password: ${DB_PASSWORD:S87zuyNLIEXcx76J}
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
        
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
              
  mail:
    host: ${MAIL_HOST:smtp.sendgrid.net}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:apikey}
    password: ${MAIL_PASSWORD:your-sendgrid-api-key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

# File Upload Configuration
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

# Payment Configuration
stripe:
  api-key: ${STRIPE_API_KEY:your-stripe-api-key}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:your-webhook-secret}

# Email Configuration
sendgrid:
  api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key}
  from-email: ${FROM_EMAIL:noreply@doctorplus.com}

# Logging
logging:
  level:
    com.doctorplus: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/doctorplus.log

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized